version: '3.9'

services:
  flask:
    build: .
    container_name: flask_app
    expose:
      - "5000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment:
      - GOOGLEAPI=${GOOGLEAPI}                   
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:varun2573@postgres:5432/Sat_infotech  
    networks:
      - app-net

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment:
      - GOOGLEAPI=${GOOGLEAPI}
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:varun2573@postgres:5432/Sat_infotech 
    networks:
      - app-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=Sat_infotech              
      - POSTGRES_USER=postgres                
      - POSTGRES_PASSWORD=varun2573           
    volumes:
      - pgdata:/var/lib/postgresql/data      
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  pgdata:
